apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: groupcache-powered-backend-role
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
    verbs:
      - 'get'
      - 'list'
