apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groupcache-powered-backend-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: groupcache-powered-backend-role
  apiGroup: rbac.authorization.k8s.io
