apiVersion: v1
kind: Service
metadata:
  name: groupcache-powered-backend-service
spec:
  selector:
    app: groupcache-powered-backend
  ports:
    - protocol: TCP
      port: 80          # The port on which the service will be accessible within the cluster
      targetPort: 3000  # The port on which your backend application is listening
  type: ClusterIP  # Use ClusterIP to expose the service within the cluster