---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    metadata:
      labels:
        app: k6-load-test
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command:
            - "/bin/sh"
            - "-c"
            - "k6 run /etc/k6/load-test.js"
          volumeMounts:
            - name: k6-scripts
              mountPath: /etc/k6
      restartPolicy: Never
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-scripts-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts-configmap
data:
  load-test.js: |-
    import http from 'k6/http';
    import {sleep} from 'k6';
    
    export let options = {
        stages: [
            {duration: '1m', target: 50},  // Ramp-up to 50 users over 1 minute
            {duration: '3m', target: 50},  // Stay at 50 users for 3 minutes
            {duration: '1m', target: 0}    // Ramp-down to 0 users over 1 minute
        ]
    };
    
    export default function () {
        let randomKey = (Math.random() + 1).toString(36).substring(2);
        let url = `http://groupcache-powered-backend-service:80/get/${randomKey}`;
        const res = http.get(url);
        check(res, {
            'is OK 200': (r) => r.status === 200,
        });
    }