[package]
name = "groupcache"
version = "0.1.0"

[dependencies]
anyhow = "1.0.72"
hashring = "0.3.2"
axum = "0.6.20"
tokio = { version = "1.12.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
