[package]
name = "groupcache"
version = "0.1.0"
edition = "2021"

[dependencies]
hashring = "0.3.2"
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }