namespaceOverride: "default"

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

global:
  ## How frequently to scrape targets by default
  ##
  scrape_interval: 15s
  ## How long until a scrape request times out
  ##
  scrape_timeout: 5s
  ## How frequently to evaluate rules
  ##
  evaluation_interval: 3m